### ISSUE TITLE
Limiting bot commands to a specific text-channel 

### ISSUE THREAD

**Issue by Ashwinshankar98** [Ashwinshankar98/ClassMateBot#12]
can be helpful for detecting spam and banning those unwanted users.

**Comment by Ashwinshankar98** [comment]
@ithaaswin @shakthinandana @saikaushik1997 @kailash1998s  Let me know if this is necessary. will move on from there.

**Comment by kailash1998s** [comment]
Don't think it's needed because already we have grouped the commands to different channels

**Comment by ithaaswin** [comment]
Yes and I think this issue can be closed now.

**Comment by kailash1998s** [comment]
There are some BOT commands that don't fall under any of our channel commands like Cog loading maybe an explicit channel for such commands can be created in future.
