### ISSUE TITLE
Duplicate Roles

### ISSUE THREAD

**Issue by Ashwinshankar98** [Ashwinshankar98/ClassMateBot#24]
![WhatsApp Image 2021-11-26 at 5 51 48 PM](https://user-images.githubusercontent.com/28307941/143660843-fbc40028-2414-4642-b4c5-7ca233d584a3.jpeg)

**Comment by kailash1998s** [comment]
I have checked this issue and happens only when we kick the BOT and re-add it. This can only be overcome if we make sure BOT deletes roles it created when it leaves. For now, this functionality is not provided by discord python API. You will have to manually delete the roles each time the BOT is removed.
